Created Person, Student and Teacher classes
Asiimwe-Mark/OOP_School_Library pull request #1
Opened 2023-10-09 20:19 UTC by As1imwe-Mark

- In this project, I created the three required classes with their respective instance variables, getters, and setters as stated in the project requirements

2023-10-09 21:39 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @As1imwe-Mark, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-09 21:39 UTC, Qoosim commented on person.rb
> +end
- [OPTIONAL] Great job creating `Person`. It is important to adapt the best practice for arranging your code very well. It is recommended to set your Getter or Setter after class declaration, not after initialization. 
- [ ] It is required to set Setter for id and initialize it in your method
`attr_reader :id `

```
def initialize(age, name = "Unknown", parent_permission = true)
    @id = Random.rand(1..1000)
    @age = age
    @name = name
    @parent_permission = parent_permission
  end
```

2023-10-09 21:39 UTC, Qoosim commented on student.rb
> +  def initialize(_id, age, classroom, name = 'Unknown', parent_permission: true)
- [ ] Once the `id` is set and initialized in the `Person` class, it would not need here again. Since `Student` inherits from `Person` class

2023-10-09 21:39 UTC, Qoosim commented on teacher.rb
> +  def initialize(_id, age, specialization, name = 'Unknown', parent_permission: true)
- [ ] Samething here

2023-10-10 12:56 UTC, TadesseDev approved these changes
### Hi @As1imwe-Mark 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![AmazingCreepyFrogmouth-max-1mb](https://user-images.githubusercontent.com/69077061/255314805-13569584-0c0e-4b38-a0bd-94d901ba8a1e.gif)




## Highlights
 - [x] Good job making the changes requested by the previous code reviewer. ✅


## Optional suggestions

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 13:59 UTC, merged